config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments
  validates :name, presence: true

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.moola.first
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
#DELETE test_variable ONCE FINISHED
    @test_variable = 42
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    #@comments = @product.comments.order("created_at DESC")
    @comments = @product.comments.paginate(page: params[:page], per_page: 3).order("created_at DESC")
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <div class="row">
      <hr>
      <p>
        <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
        <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </p>
      <div class= "rated" data-score="<%= comment.rating %>"></div>
<!--  <p><%= "Rating: #{comment.rating}/5" %></p> #using raty to display ratings-->
      <br><%= comment.body %>
    </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :colour %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :colour %>
    <%= f.text_field :colour %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_loopproducts.html.erb
<div class="col-md-4 col-sm-2">
  <%= image_tag(product.image_url, class: "img-responsive") %>
  <h3><%= product.name %></h3>
  <p><%= product.description %></p>
  <p><%= product.colour %></p>
  <strong><%= product.price %></strong>
  <%= link_to 'Show', product %>
  <%= link_to 'Edit', edit_product_path(product) %>
  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
</div><!-- /col -->

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build]) do |f| %>

      <%= f.label(:body, "Comments")%><br>
      <%= f.text_area :body, size: "30x3",placeholder: "Write your review here", style: "resize:none" %>
      <br><br>
      <div class="rating"></div>
      <br>
      <%= f.submit "Submit" %>

  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<!-- DELETE FOLLOWING TEST VARIABLE ONCE FINISHED -->
<%= @test_variable %>
<!-- small loop to show number + 1
<% paragraph_number = 1 %>
<% 8.times do %>
  <p>This is paragraph number <%= paragraph_number %></p>
  <% paragraph_number = paragraph_number + 1 %>
<% end %>
-->

<div class="container">
  <div class="row">
    <% @products.each do |product| %>
    <!--  <div class="col-xs-6 col-sm-4"> -->
      <%= render partial: 'loopproducts', locals: {product: product} %>
    <% end %><!-- end loop -->
  </div><!-- row -->
</div><!-- container -->

<!-- TABLE FOR REFERENCE
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <h1><%= @product.name %></h1>
  <div class="row">
    <div class= "col-xs-8 col-md-6">
      <a href="/static_pages/about">
        <%= image_tag(@product.image_url, class: "thumbnail img-responsive", alt:"too cool")%>
      </a>
    </div>
  </div>
</div>

<div class="container">

  <strong>Name:</strong>
  <%= @product.name %><br>


<br>
  <strong>Description:</strong>
  <%= @product.description %>


<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<h4>Average Rating:</h4>
<div class="rated" data-score="<%= @product.average_rating %>"></div>
<br>

<%= render partial: 'new_comment'%>
<%= render partial: 'comments'%>

<div class= "flickr_pagination">
  <%= will_paginate @comments %>
</div>

</div>
<!--<%= @product.highest_rating_comment %>
    <%= @product.lowest_rating_comment %> -->


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

<!--
<%= link_to "moolazz", static_pages_contact_path %>
<a href="http://localhost:3000/products/3/edit">here</a>
-->